{
 "title": "Transcendence_db_pong",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Matches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transcendence_matches_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Register Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transcendence_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active friendships",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transcendence_active_friendships",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Send messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transcendence_chat_messages_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}