{
 "title": "Dashboard Transcendence",
 "refresh": "5s",
 "panels": [
  {
   "title": "Usuarios",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as \"Players\" FROM PLAYER;"
    }
   ]
  },
  {
   "title": "Partidos",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as \"MATCHS\" FROM MATCH;"
    }
   ]
  },
  {
   "title": "Organizaciones",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as \"ORGANIZATIONS\" FROM ORGANIZATION;"
    }
   ]
  }
 ]
}